### ISSUE TITLE
Open error 

### ISSUE THREAD

**Issue by JavaStarter** [RedCommissary/altium-library#2]
After openning any .SchLib Library, Altium shows an error  "FontStyleNotFound". ISOCPEUR and GOST fonts are installed. 
![OpenError](https://user-images.githubusercontent.com/14937065/63098162-f3e07680-bf7a-11e9-90d4-9d8d71b66459.png)

**Comment by Nordic-Energy** [comment]
Hi!
[Download ISOCPEUR.](https://drive.google.com/open?id=1G8LglCGRg-ghN8Qw6fCRN40oJ8pYA3gd)
This problem is familiar to me. You need to install the correct font ISOCPEUR, I attached it above. Did this solve your problem?

**Comment by JavaStarter** [comment]
Hello! Yes, really, with this font your library is worked. Thank you!
