### ISSUE TITLE
Просьба именовать файлы правил соответственно классу точности

### ISSUE THREAD

**Issue by KonevDN** [RedCommissary/altium-library#47]
Я сначала обрадовался что у вас имеется папка rules-pcb с фалами , которые содержат правила трассировки для разных классов точности. Однако нужно прилагать много усилий чтобы в них разобраться.  

Можно ли понять какой файл соответствует какому либо классу точности с таким наименованием? 
rules-pcb-8mil.RUL
rules-pcb-6mil.RUL
rules-pcb-4mil.RUL
-нет нельзя.

если бы вы назвали их хотя бы 
Класс1.RUL или Class1.RUL
Класс2.RUL или Class2.RUL
Класс3.RUL или Class3.RUL
-то это было бы логично, цивилизованно - правильно. 

вот тут https://www.rezonit.ru/upload/files/dopuski-plat.pdf  сказано что существует 5 классов точности, какому из них соответствуют 3 ваших файла? -не понять без потери времени на то, на что терять время не нужно, вы же сами хотели дать людям сэкономить время и предоставили свои фалы с правилами. Так же в этой статье сказано, что классы точности заданы ГОСТом, поэтому логично будет и в файлах это указать, ведь классы точности могут задаваться разными министерствами, например вот предлагаю хорошее наименование:
Класс_точности1,ГОСТ_23751-86.RUL
Класс_точности2,ГОСТ_23751-86.RUL
Класс_точности3,ГОСТ_23751-86.RUL
-не бойтесь писать русские буквы в названиях файлов! Altium Designer хорошо умеет их обрабатывать. 

Спасибо за внимание и за вашу работу.

**Comment by RedCommissary** [comment]
Добрый день!
Я резонит не пользуюсь сам и ни кому не советую, очень странные и неадекватные ребята. Самое главное их видение классов точности такое же странное и сильно отличается от общемировых стандартов. 4/6/8 mil - это стандарты по которым работают и азиатские заводы и европейцы и Штаты.

Что касается соответствия классов, то в первом приближение оно так:
- 4 mil это то, что у резонита именуется 0.1/0.1 мм или 5-й класс, во много оно совпадает с общепринятыми ограничениями, но вот via и соотношение "толщина фольги/зазор" резонит требует более простой, хотя любой китайский лоукостер может сделать 4 mil и на 2 Oz (70 мкм) меди, а резонит уже нет;

- 6 mil это резонитовский "стандартный" или 4-й класс. Тут тоже есть свои приколы со стороны резонита, например, они не могут его выдержать на повышенных толщинах меди или 0.6/0.3 via делают криво или вообще просят поменять;

- 8 mil это собственно 0.2/0.2 мм или то, что резонит просит использовать как только толщина меди становится 2  Oz (70 мкм) или 3 Oz (105 мкм), а китайцы на таких пределах могу и 10 Oz в принципе. Сам набор правил больше актуален для силовой электроники.

Набор правил 4/6/8 mil идет на любом НЕ российском заводе, да и люди в основном заказывают в Китае. С тем же резонитом вынуждены работать в основном гос. компании и прочие большие организации, но там обычно есть свои стандарты, наборы правил, шаблоны, то есть моя работа для них вообще не актуальна.

Русские буквы это наверное последнее, что появится в файлах CAD-а)) Как минимум git очень неадекватно воспринимает кириллицу и потом невозможно работать с ветками и диффами.
