### ISSUE TITLE
Проблема с переворотом коннекторов

### ISSUE THREAD

**Issue by YuryKoshkarov** [RedCommissary/altium-library#5]
Заголовки у всех коннекторов не переворачиваются

![img-2020-04-06-10-45-32](https://user-images.githubusercontent.com/47121375/78535110-49141580-77f4-11ea-8bc0-601d295aff6f.png)

**Comment by gardarica** [comment]
Разъемы в принципе не должны зеркалиться по Y, только по Х. Это изначально так задумано, все таки подпись контактов и цепей должно располагаться сверху и выглядеть как таблица
